build:
  environment:
    php:
      version:  "7.4"
  nodes:
   coverage:
     tests:
       override:
         - command: composer phpunit-coverage-xml
           coverage:
             file: coverage.xml
             format: clover
   analysis:
     tests:
       override:
         - php-scrutinizer-run